name: 🚀 Daily Cloudflare Build Trigger

on:
  schedule:
    - cron: '30 1 * * *' # Đúng 01:30 sáng hằng ngày theo giờ UTC
  workflow_dispatch:

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - name: 🔥 Trigger Cloudflare Pages Deploy Hook
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/workers/builds/deploy_hooks/1f18ced9-a75b-4cf4-ac83-9dc83df99502"