name: 🚀 Daily Cloudflare Pages Redeploy

on:
  schedule:
    - cron: '30 1 * * *' # 01:30 UTC = 08:30 Việt Nam
  workflow_dispatch:

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Cloudflare Pages Deploy Hook
        run: curl -X POST "${{ secrets.CLOUDFLARE_DEPLOY_HOOK_URL }}"